name: Cypress tests

on: 
  workflow_dispatch:
  pull_request:

env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.me
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.me
  FORESIGHT_LOG_LEVEL: debug

jobs:
  test1:
    name: Cypress test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Collect Workflow Telemetry
        if: always()
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FORESIGHT_APIKEY_US }}

      - name: Use Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: install dependencies and verify Cypress
        run: |
          npm install
      
      - name: Cypress tests
        run: npm run test
      
      # - name: Remove git folder
      #   run: |
      #     echo "Githob workspace $GITHUB_WORKSPACE"
      #     echo "Listing files in $GITHUB_WORKSPACE ..."
      #     ls -al $GITHUB_WORKSPACE
      #     echo "Removing $GITHUB_WORKSPACE/.git ..."
      #     rm -rf $GITHUB_WORKSPACE/.git
      #     echo "Listing files in $GITHUB_WORKSPACE ..."
      #     ls -al $GITHUB_WORKSPACE

      - name: Thundra Registry
        run: |
          npm config set registry ${{ secrets.THUNDRA_REGISTRY }}
          npm config set _auth ${{ secrets.THUNDRA_REGISTRY_AUTH }}

      - name: Analyze Test and/or Coverage Results
        if: always()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.FORESIGHT_APIKEY_US }}
          test_framework: cypress
          test_format: junit
          test_path: ./results/foresight-test-*.xml
          coverage_format: LCOV/TXT
          coverage_path: ./coverage/lcov.info
          working_directory: ./
          cli_version: 123.457.2