name: Cypress tests

on: 
  workflow_dispatch:

env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.us
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.us
  FORESIGHT_LOG_LEVEL: debug

jobs:
  test1:
    name: Cypress test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Collect Workflow Telemetry
      if: always()
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_APIKEY_US }}

    - name: Use Node.js v14
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: install dependencies and verify Cypress
      run: |
        npm install
    
    - name: Cypress tests
      run: npm run test

    - name: Analyze Test and/or Coverage Results
      if: always()
      uses: runforesight/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_APIKEY_US }}
        test_framework: cypress
        test_format: junit
        test_path: ./results/foresight-test-*.xml
        coverage_format: LCOV/TXT
        coverage_path: ./coverage/lcov.info